### ISSUE TITLE
Add functions to ownership list

### ISSUE THREAD

**Issue by clrcrl** [Squarespace/pgbedrock#30]
Functions, like tables and schemas, have an owner, which should also be managed by pgbedrock.

For example
```
jdoe:
    ...
    owns:
        schemas:
            - finance_reports
        tables:
            - finance_reports.Q2_revenue
            - finance_reports.Q2_margin
        functions:
            - f_cast_string_as_number
```
