### ISSUE TITLE
Add documentation about how to use pgbedrock in a docker compose setup

### ISSUE THREAD

**Issue by zfrenchee** [Squarespace/pgbedrock#48]
I have
```
version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: DB
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - "./pgdata:/var/lib/postgresql/data"
```

How do I properly add pgbedrock to my compose setup?
