### ISSUE TITLE
Setting password commented out

### ISSUE THREAD

**Issue by acarl005** [Squarespace/pgbedrock#64]
I tried to create a role with a password.

```yaml
student:
  can_login: yes
  is_superuser: no
  attributes:
    - PASSWORD "{{ env['STUDENT_PASSWORD'] }}"
  privileges:
    schemas:
      read:
        - challenges
    tables:
      read:
        - challenges.*
```

I provided `STUDENT_PASSWORD` in the environment. This is the generated config. The password setting was skipped for some reason:

```sql
--------------------------------
--- Configuring attributes -----
--------------------------------

CREATE ROLE "student";
ALTER ROLE "student" WITH LOGIN;
--ALTER ROLE "student" WITH ENCRYPTED PASSWORD '******';
```

How can I get pgbedrock to actually set the password for my new user?
